package com.exrade.models.notification;

import java.util.Arrays;
import java.util.List;

public enum NotificationType {

    NEGOTIATION_INVITATION_RECEIVED,
    NEGOTIATION_INVITATION_UPDATED,
    NEGOTIATION_JOIN_REQUEST_UPDATED,
    NEGOTIATION_JOIN_REQUESTED,
    NEGOTIATION_USER_JOINED,
    NEGOTIATION_INFO_MESSAGE_RECEIVED,
    NEGOTIATION_MESSAGE_RECEIVED,
    NEGOTIATION_CREATED,
    NEGOTIATION_AGREED,
    NEGOTIATION_NOT_AGREED,
    NEGOTIATION_TO_CREATE_REMINDER, // N
    //NEGOTIATION_TO_JOIN_REMINDER, // N
    NEGOTIATION_PENDING_JOIN_REQUEST_REMINDER, // N
    NEGOTIATION_PENDING_INVITATION_REMINDER,
    NEGOTIATION_INVITE_PARTICIPANT_REMINDER, // N
    NEGOTIATION_QII_DATA_RECEIVED,

    WORKGROUP_MEMBER_ADDED,
    WORKGROUP_POST_CREATED,
    WORKGROUP_COMMENT_CREATED,
    WORKGROUP_NEGOTIATION_ADDED,

    WORKGROUP_NEGOTIATION_REMOVED,
    WORKGROUP_MEMBER_REMOVED,
    WORKGROUP_CREATED,
    PROFILE_MEMBERSHIP_INVITATION_RECEIVED,
    PROFILE_MEMBERSHIP_INVITATION_UPDATED,
    PROFILE_PENDING_MEMBERSHIP_INVITATION_REMINDER, // N
    PROFILE_NOT_COMPLETED_REMINDER, // N
    PROFILE_NOT_LOGGEDIN_REMINDER, // N
    PROFILE_MEMBERSHIP_EXPIRING_REMINDER, // N
    PROFILE_QUOTA_FINISHING_REMINDER, // N
    PROFILE_TRIAL_FINISHING_REMINDER,

    AUTHORISATION_REQUESTED,
    AUTHORISATION_PENDING_REMINDER,

    REVIEW_REQUESTED,
    REVIEW_PENDING_REMINDER,

    SIGNATURE_COMPLETED,
    SIGNATURE_PENDING_REMINDER,

    CONTRACT_CREATED,
    CONTRACT_MEMBER_ADDED,
    CONTRACT_MEMBER_REMOVED,
    CONTRACT_EXPIRING_REMINDER,
    CONTRACT_TERMINATION_NOTICE_DEADLINE_REMINDER,
    CONTRACT_RENEWED, // N
    CONTRACT_NEXT_RENEWAL_REMINDER, // N

    USER_PASSWORD_CHANGED,
    USER_PASSWORD_RESET_REQUESTED,
    USER_SIGNUP_CONFIRMATION_REQUIRED,
    USER_WELCOME_NOTIFICATION,
    INFORMATION_MODEL_MEMBER_ADDED,
    NEGOTIATION_MEMBER_ADDED,


    TRAK_CREATED,
    TRAK_UPDATED,
    TRAK_RESPONSE_CREATED,
    TRAK_RESPONSE_UPDATED,
    TRAK_APPROVAL_CREATED,
    TRAK_APPROVAL_UPDATED,

    UPCOMING_LIFE_CYCLE_EVENTS,
    IMPORT_FINISHED,

    PAYMENT_PENDING,
    PAYMENT_COMPLETE,

    PAYMENT_SUBSCRIBED,
    PAYMENT_UN_SUBSCRIBED,

    CLAUSE_STATUS_UPDATED;

    public static final List<NotificationType> NegotiationNotifications = Arrays.asList(NEGOTIATION_INFO_MESSAGE_RECEIVED,
            NEGOTIATION_INVITATION_UPDATED,
            NEGOTIATION_INVITATION_RECEIVED,
            NEGOTIATION_MESSAGE_RECEIVED,
            NEGOTIATION_JOIN_REQUEST_UPDATED,
            NEGOTIATION_JOIN_REQUESTED,
            NEGOTIATION_USER_JOINED,
            NEGOTIATION_CREATED,
            NEGOTIATION_AGREED,
            NEGOTIATION_NOT_AGREED,
            NEGOTIATION_TO_CREATE_REMINDER,
            NEGOTIATION_PENDING_JOIN_REQUEST_REMINDER,
            NEGOTIATION_PENDING_INVITATION_REMINDER,
            NEGOTIATION_INVITE_PARTICIPANT_REMINDER,
            NEGOTIATION_QII_DATA_RECEIVED,
            NEGOTIATION_MEMBER_ADDED
    );

    public static final List<NotificationType> WorkGroupNotifications = Arrays.asList(WORKGROUP_MEMBER_ADDED,
            WORKGROUP_POST_CREATED,
            WORKGROUP_COMMENT_CREATED,
            WORKGROUP_NEGOTIATION_ADDED,
            WORKGROUP_NEGOTIATION_REMOVED,
            WORKGROUP_MEMBER_REMOVED,
            WORKGROUP_CREATED);

    public static final List<NotificationType> ProfileNotifications = Arrays.asList(PROFILE_MEMBERSHIP_INVITATION_RECEIVED,
            PROFILE_MEMBERSHIP_INVITATION_UPDATED,
            PROFILE_PENDING_MEMBERSHIP_INVITATION_REMINDER,
            PROFILE_NOT_COMPLETED_REMINDER,
            PROFILE_NOT_LOGGEDIN_REMINDER,
            PROFILE_MEMBERSHIP_EXPIRING_REMINDER,
            PROFILE_QUOTA_FINISHING_REMINDER,
            PROFILE_TRIAL_FINISHING_REMINDER);

    public static final List<NotificationType> AuthorisationNotifications = Arrays.asList(AUTHORISATION_REQUESTED,
            AUTHORISATION_PENDING_REMINDER);

    public static final List<NotificationType> ReviewNotifications = Arrays.asList(REVIEW_REQUESTED,
            REVIEW_PENDING_REMINDER);

    public static final List<NotificationType> SignatureNotifications = Arrays.asList(SIGNATURE_COMPLETED,
            SIGNATURE_PENDING_REMINDER
    );

    public static final List<NotificationType> ContractNotifications = Arrays.asList(CONTRACT_EXPIRING_REMINDER,
            CONTRACT_CREATED,
            CONTRACT_MEMBER_ADDED,
            CONTRACT_MEMBER_REMOVED,
            CONTRACT_TERMINATION_NOTICE_DEADLINE_REMINDER,
            CONTRACT_RENEWED,
            CONTRACT_NEXT_RENEWAL_REMINDER);

    public static final List<NotificationType> UserNotifications = Arrays.asList(USER_PASSWORD_CHANGED,
            USER_PASSWORD_RESET_REQUESTED,
            USER_SIGNUP_CONFIRMATION_REQUIRED,
            USER_WELCOME_NOTIFICATION);

    public static final List<NotificationType> InformationModelNotifications = Arrays.asList(INFORMATION_MODEL_MEMBER_ADDED);

    public static final List<NotificationType> TrakNotifications = Arrays
            .asList(TRAK_CREATED, TRAK_UPDATED, TRAK_RESPONSE_CREATED, TRAK_RESPONSE_UPDATED, TRAK_APPROVAL_CREATED, TRAK_APPROVAL_UPDATED);
    public static final List<NotificationType> ClauseNotifications = Arrays.asList(CLAUSE_STATUS_UPDATED);

    public static final List<NotificationType> PaymentNotifications = Arrays.asList(PAYMENT_PENDING, PAYMENT_COMPLETE);

}
