package com.exrade.models.event;

public enum LogEventType {
	MESSAGE_SENT, 
	MESSAGE_RECEIVED,
	TIME_EVENT,
	TRANSITION_TAKEN,
	PARTICIPANT_JOINED,
	PARTICIPANT_LEFT,
	ADMISSION_REQUEST_RECEIVED,
	PROFILE_STATUS,
	USER_INVITED,
	INVITATION_ACCEPTED,
}
