package com.exrade.models.contract;

public enum ContractStatus {

	ACTIVE,
	ACTIVE_FUTURE,
	CANCELLED,
	EXPIRED, 
	IN_DISPUTE,
	LEGALLY_PROSCRIBED,
	SUCCESSFULLY_ENDED,
	TO_BE_REISSUED,
	UNDER_AMENDMENT,
	UNDER_EVALUATION,
	UNDER_RENEGOTIATION,
	UNDER_RENEWAL, 
	UNSUCCESSSFULLY_ENDED;
	
}
